config/routes.rb
Inventory3::Application.routes.draw do
  resources :gross_revenues

  get "sales/sale_report"
  get "products/stock_report"
  get "statics/welcome"
  get "statics/admin"
  get "products/clerk"
  resources :total_revenues

  resources :sales

  resources :products

  resources :orders

end

app/models/gross_revenue.rb
class GrossRevenue < ActiveRecord::Base
  has_many :sales

  def total_g_revenue
    total_count = 0
    Sale.all.each do |c|
      total_count += c.revenue
    end
    total_count
  end
end

app/controllers/gross_revenues_controller.rb
class GrossRevenuesController < ApplicationController
  before_action :set_gross_revenue, only: [:show, :edit, :update, :destroy]

  # GET /gross_revenues
  # GET /gross_revenues.json
  def index
    @gross_revenues = GrossRevenue.all
  end

  # GET /gross_revenues/1
  # GET /gross_revenues/1.json
  def show
  end

  # GET /gross_revenues/new
  def new
    @gross_revenue = GrossRevenue.new
  end

  # GET /gross_revenues/1/edit
  def edit
  end

  # POST /gross_revenues
  # POST /gross_revenues.json
  def create
    @gross_revenue = GrossRevenue.new(gross_revenue_params)

    respond_to do |format|
      if @gross_revenue.save
        format.html { redirect_to @gross_revenue, notice: 'Gross revenue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gross_revenue }
      else
        format.html { render action: 'new' }
        format.json { render json: @gross_revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gross_revenues/1
  # PATCH/PUT /gross_revenues/1.json
  def update
    respond_to do |format|
      if @gross_revenue.update(gross_revenue_params)
        format.html { redirect_to @gross_revenue, notice: 'Gross revenue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gross_revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gross_revenues/1
  # DELETE /gross_revenues/1.json
  def destroy
    @gross_revenue.destroy
    respond_to do |format|
      format.html { redirect_to gross_revenues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gross_revenue
      @gross_revenue = GrossRevenue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gross_revenue_params
      params[:gross_revenue]
    end
end

app/helpers/gross_revenues_helper.rb
module GrossRevenuesHelper
end

app/views/gross_revenues/_form.html.erb
<%= form_for(@gross_revenue) do |f| %>
  <% if @gross_revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gross_revenue.errors.count, "error") %> prohibited this gross_revenue from being saved:</h2>

      <ul>
      <% @gross_revenue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gross_revenues/edit.html.erb
<h1>Editing gross_revenue</h1>

<%= render 'form' %>

<%= link_to 'Show', @gross_revenue %> |
<%= link_to 'Back', gross_revenues_path %>

app/views/gross_revenues/index.html.erb
<hr />
<%= link_to "Home", statics_welcome_path%>
<%= link_to "Product", products_path %>
<%= link_to "Order", orders_path %>
<%= link_to "Sale", sales_path %>
<%= link_to "Sale Report", sales_sale_report_path %>
<%= link_to "Low on Stock Report", products_stock_report_path %>
<hr />
<h1>Total Cost of Good Sold</h1>

<table>
  <thead>
  <tr>
    <th>Total gross revenue</th>

  </tr>
  </thead>

  <tbody>
  <% @gross_revenues.each do |total_revenue| %>
      <tr>
        <td><%= number_to_currency(total_revenue.total_g_revenue)%>

      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/gross_revenues/new.html.erb
<h1>New gross_revenue</h1>

<%= render 'form' %>

<%= link_to 'Back', gross_revenues_path %>

app/views/gross_revenues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gross_revenue_path(@gross_revenue) %> |
<%= link_to 'Back', gross_revenues_path %>