config/routes.rb
Inventory3::Application.routes.draw do
  resources :gross_revenues

  get "sales/sale_report"
  get "products/stock_report"
  get "statics/welcome"
  get "statics/admin"
  get "products/clerk"
  resources :total_revenues

  resources :sales

  resources :products

  resources :orders

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :sales
  has_many :orders
  has_many :sale_reports



  def total
    listing = Sale.all
    listing.group_by(&:product_id).to_a.sum{|a| (a.sold)}
  end

  def sum_sold
    sales.sum(:sold)
  end

  def sum_order
    orders.sum(:order_quanity)
  end

  def update_stock
    update = quanity - sum_sold + sum_order
  end

  def below_five
    if update_stock< minimum
      "RESTOCK"
    else ""
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  def stock_report
    @products = Product.all
    render :action => :index, :layout => "product"
  end
  def clerk
    @products = Product.all
    render :action => :index, :layout => "clerk_product"
  end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quanity, :price, :minimum)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quanity %><br>
    <%= f.number_field :quanity %>
  </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.number_field :price %>
    </div>
  <div class="field">
    <%= f.label :minimum %><br>
    <%= f.number_field :minimum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/clerk.html.erb
<%= render :action => 'products/index', :layout => 'product' %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= link_to "Home", statics_welcome_path%>
<%= link_to "Order", orders_path %>
<%= link_to "Sale", sales_path %>
<%= link_to "Sale Report", sales_sale_report_path %>
<%= link_to "Low on Stock Report", products_stock_report_path %>
<%= link_to "Total Gross Revenue", total_revenues_path %>
<hr />
<h1>Products Available</h1>

<table border="2">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quanity</th>
      <th>Price</th>
      <th>Minimum</th>
      <th>Restock</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.quanity - product.sum_sold + product.sum_order %></td>
        <td><%= number_to_currency(product.price)	  %></td>
        <td><%= product.minimum %></td>
        <td><%= product.below_five %></td>

        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Quanity:</strong>
  <%= @product.quanity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Minimum:</strong>
  <%= @product.minimum %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/stock_report.html.erb
<%= render :action => 'products/index', :layout => 'product' %>