config/routes.rb
Inventory3::Application.routes.draw do
  resources :gross_revenues

  get "sales/sale_report"
  get "products/stock_report"
  get "statics/welcome"
  get "statics/admin"
  get "products/clerk"
  resources :total_revenues

  resources :sales

  resources :products

  resources :orders

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :products
  belongs_to :total_revenue
  belongs_to :sale_report







  def self.search(search,searchA)
    if search
      # #Sale.where(["date <= :start_date", {:start_date => "#{search}"}])
      Sale.where([" date <= :end_date AND date >= :start_date", {:start_date => "#{search}",:end_date => "#{searchA}"}])
    else
      Sale.all
    end
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @sales = Sale.search(params[:search],params[:searchA])

  end
  def sale_report

    @sales = Sale.all
    @sales = Sale.search(params[:search],params[:searchA])
    render :action => :index, :layout => "report"

  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:product_id, :sold, :price, :date, :revenue)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.number_field :sold %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

   <div class="field">
    <%= f.label :revenue %><br>
   <%= f.number_field :revenue %><br>

   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<%= link_to "Home", statics_welcome_path%>
<%= link_to "Order", orders_path %>
<%= link_to "Product", products_path %>
<%= link_to "Sale Report", sales_sale_report_path %>
<%= link_to "Low on Stock Report", products_stock_report_path %>
<%= link_to "Total Gross Revenue", total_revenues_path %>
<hr />
<h1>List of Good Sold</h1>

<%= form_tag sales_path, :method => 'get' do %>
    <p>
      Start Date:
      <%= date_field_tag :search, params[:search] %>
      End Date:
      <%= date_field_tag :searchA, params[:searchA] %>
      <%= submit_tag "Search" %>
    </p>
<% end %>
<table border="2">
  <thead>
    <tr>
      <th>Product</th>
      <th>Sold</th>
      <th>Price</th>
       <th>Date</th>
      <th>Revenue</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.product_id %></td>
        <td><%= sale.sold %></td>
        <td><%= sale.price	  %></td>
         <td><%= sale.date %></td>
        <td><%= number_to_currency(sale.revenue)  %></td>
         <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/sale_report.erb
<%= render :action => 'sales/index', :layout => 'report' %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @sale.product_id %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @sale.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sale.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>